apiVersion: 1

datasources:
  - name: E5-Metrics
    uid: e5metrics
    type: yesoreyeram-infinity-datasource
    access: proxy
    isDefault: false
    jsonData:
      datasource_mode: 'basic'
    version: 1
