<?php

declare(strict_types=1);

namespace App\Console\Commands;

use App\Domains\Users\Models\User;
use Illuminate\Console\Command;

/**
 * Generate (or check) the `frontend/app/utils/avatar.constants.js`
 * module from `User::AVATAR_MAX_KB` and the accepted MIME types.
 *
 * The model constant is the single source of truth: this command emits
 * `AVATAR_MAX_KB`, `ACCEPTED_MIMES`, and `ACCEPTED_MIME_TYPES` so the
 * frontend cannot drift from the backend.
 *
 * `--check` is the CI guard: it returns `Command::FAILURE` (exit
 * code 1) when the committed artifact would change.
 *
 * Usage:
 *   php artisan avatar:generate-frontend-constants              # write the file
 *   php artisan avatar:generate-frontend-constants --check    # CI mode
 *   php artisan avatar:generate-frontend-constants --output=.. # custom path
 */
final class GenerateAvatarConstantsCommand extends Command
{
    protected $signature = 'avatar:generate-frontend-constants
                            {--check : Exit non-zero if the generated file would differ from the committed one (CI mode)}
                            {--output= : Override the destination path (default: frontend/app/utils/avatar.constants.js)}';

    protected $description = 'Generate (or check) frontend/app/utils/avatar.constants.js from User::AVATAR_MAX_KB';

    private const DEFAULT_OUTPUT = 'frontend/app/utils/avatar.constants.js';

    // must match UpdateProfileRequest + StoreUserAvatarRequest
    private const ACCEPTED_MIMES = ['jpg', 'jpeg', 'png', 'webp'];

    private const MIME_TYPE_MAP = [
        'jpg' => 'image/jpeg',
        'jpeg' => 'image/jpeg',
        'png' => 'image/png',
        'webp' => 'image/webp',
    ];

    public function handle(): int
    {
        $generated = $this->buildConstantsFile();
        $path = $this->resolveOutputPath();

        if ($this->option('check')) {
            $current = is_file($path) ? (string) file_get_contents($path) : '';
            if ($current === $generated) {
                $this->info('avatar.constants.js is in sync with User::AVATAR_MAX_KB.');

                return self::SUCCESS;
            }

            $this->error('avatar.constants.js drift detected. Regenerate with: php artisan avatar:generate-frontend-constants');

            return self::FAILURE;
        }

        if (! is_file($path) || (string) file_get_contents($path) !== $generated) {
            file_put_contents($path, $generated);
            $this->info("Wrote {$path}");
        } else {
            $this->info("{$path} is already in sync.");
        }

        return self::SUCCESS;
    }

    /**
     * Build the generated file body deterministically.
     */
    private function buildConstantsFile(): string
    {
        $maxKb = (int) User::AVATAR_MAX_KB;
        $mimes = self::ACCEPTED_MIMES;
        sort($mimes, SORT_STRING);

        $mimeTypes = array_unique(array_values(array_map(
            static fn (string $ext): string => self::MIME_TYPE_MAP[$ext],
            $mimes,
        )));
        sort($mimeTypes, SORT_STRING);

        $mimesLines = implode("\n", array_map(
            fn (string $mime): string => sprintf('  %s,', $this->jsString($mime)),
            $mimes,
        ));

        $mimeTypesLines = implode("\n", array_map(
            fn (string $type): string => sprintf('  %s,', $this->jsString($type)),
            $mimeTypes,
        ));

        return <<<JS
        // AUTO-GENERATED by php artisan avatar:generate-frontend-constants.
        // DO NOT EDIT — your changes will be overwritten on the next run and CI will fail.

        /** Maximum avatar upload size in kilobytes. */
        export const AVATAR_MAX_KB = {$maxKb};

        /** Accepted avatar file extensions (lowercase, no dot). */
        export const ACCEPTED_MIMES = Object.freeze([
        {$mimesLines}
        ]);

        /** Accepted avatar MIME types (for <input type="file" accept="...">). */
        export const ACCEPTED_MIME_TYPES = Object.freeze([
        {$mimeTypesLines}
        ]);

        JS;
    }

    /**
     * Encode a PHP string as a JS double-quoted literal.
     */
    private function jsString(string $value): string
    {
        $escaped = str_replace(
            ['\\', '"', "\n", "\r", "\t", "\x08", "\f"],
            ['\\\\', '\\"', '\\n', '\\r', '\\t', '\\b', '\\f'],
            $value,
        );

        return '"'.$escaped.'"';
    }

    /**
     * Compute the absolute path to write the constants file to.
     *
     * The file lives in the sibling `frontend/` directory relative to
     * the Laravel project (`backend/`), so we resolve one level above
     * `base_path()` and guard against writing outside the project root.
     */
    private function resolveOutputPath(): string
    {
        $configured = $this->option('output');
        if (! is_string($configured) || $configured === '') {
            $configured = self::DEFAULT_OUTPUT;
        }

        // `base_path()` is the `backend/` directory; the frontend lives
        // next to it under the project root.
        $projectRoot = dirname(base_path());
        $target = $projectRoot.DIRECTORY_SEPARATOR.ltrim($configured, DIRECTORY_SEPARATOR);

        // Refuse absolute paths or paths that escape the project root.
        $real = realpath($target) ?: $target;
        $rootReal = realpath($projectRoot) ?: $projectRoot;
        if (str_contains($target, '..') || ($real !== false && ! str_starts_with($real, $rootReal))) {
            throw new \InvalidArgumentException("Refusing to write outside project root: {$target}");
        }

        return $target;
    }
}
