<?php

declare(strict_types=1);

namespace App\Console\Commands;

use App\Domains\Incidents\Enums\IncidentStatus;
use Illuminate\Console\Command;

/**
 * Generate (or check) the `frontend/app/utils/status.constants.js`
 * module from the `IncidentStatus` enum.
 *
 * The enum is the single source of truth: this command emits a
 * `STATUS_LABEL` map plus a default export so the frontend cannot
 * drift from the backend.
 *
 * `--check` is the CI guard: it returns `Command::FAILURE` (exit
 * code 1) when the committed artifact would change.
 *
 * Usage:
 *   php artisan incidents:generate-frontend-constants              # write the file
 *   php artisan incidents:generate-frontend-constants --check      # CI mode
 *   php artisan incidents:generate-frontend-constants --output=... # custom path
 */
final class GenerateFrontendConstantsCommand extends Command
{
    protected $signature = 'incidents:generate-frontend-constants
                            {--check : Exit non-zero if the generated file would differ from the committed one (CI mode)}
                            {--output= : Override the destination path (default: frontend/app/utils/status.constants.js)}';

    protected $description = 'Generate (or check) frontend/app/utils/status.constants.js from IncidentStatus';

    private const DEFAULT_OUTPUT = 'frontend/app/utils/status.constants.js';

    public function handle(): int
    {
        $generated = $this->buildConstantsFile();
        $path = $this->resolveOutputPath();

        if ($this->option('check')) {
            $current = is_file($path) ? (string) file_get_contents($path) : '';
            if ($current === $generated) {
                $this->info('status.constants.js is in sync with the IncidentStatus enum.');

                return self::SUCCESS;
            }

            $this->error('status.constants.js drift detected. Regenerate with: php artisan incidents:generate-frontend-constants');

            return self::FAILURE;
        }

        if (! is_file($path) || (string) file_get_contents($path) !== $generated) {
            file_put_contents($path, $generated);
            $this->info("Wrote {$path}");
        } else {
            $this->info("{$path} is already in sync.");
        }

        return self::SUCCESS;
    }

    /**
     * Build the generated file body deterministically.
     *
     * Cases are iterated in alphabetical order by `name` (case
     * identifier) so the output is stable across PHP versions and
     * across enum reorderings. Keys in the emitted object are
     * lexicographically sorted inside the literal.
     */
    private function buildConstantsFile(): string
    {
        $cases = IncidentStatus::cases();
        usort(
            $cases,
            static fn (IncidentStatus $a, IncidentStatus $b): int => strcmp($a->name, $b->name),
        );

        $lines = [];
        foreach ($cases as $case) {
            $lines[] = sprintf(
                '  %s: %s,',
                $this->jsString($case->frontendKey()),
                $this->jsString($case->label()),
            );
        }

        $body = implode("\n", $lines);

        return <<<JS
        // AUTO-GENERATED by php artisan incidents:generate-frontend-constants.
        // DO NOT EDIT — your changes will be overwritten on the next run and CI will fail.

        /** Map from incident status keys (string) to their canonical Spanish display label. */
        export const STATUS_LABEL = Object.freeze({
        {$body}
        });

        export default STATUS_LABEL;

        JS;
    }

    /**
     * Encode a PHP string as a JS double-quoted literal, handling the
     * subset of escape sequences we actually emit (backslashes, quotes,
     * newlines, CR, tab, backspace, form-feed, and JSON null/undefined).
     */
    private function jsString(string $value): string
    {
        $escaped = str_replace(
            ['\\', '"', "\n", "\r", "\t", "\x08", "\f"],
            ['\\\\', '\\"', '\\n', '\\r', '\\t', '\\b', '\\f'],
            $value,
        );

        return '"'.$escaped.'"';
    }

    /**
     * Compute the absolute path to write the constants file to.
     *
     * The file lives in the sibling `frontend/` directory relative to
     * the Laravel project (`backend/`), so we resolve one level above
     * `base_path()` and guard against writing outside the project root.
     */
    private function resolveOutputPath(): string
    {
        $configured = $this->option('output');
        if (! is_string($configured) || $configured === '') {
            $configured = self::DEFAULT_OUTPUT;
        }

        // `base_path()` is the `backend/` directory; the frontend lives
        // next to it under the project root.
        $projectRoot = dirname(base_path());
        $target = $projectRoot.DIRECTORY_SEPARATOR.ltrim($configured, DIRECTORY_SEPARATOR);

        // Refuse absolute paths or paths that escape the project root.
        $real = realpath($target) ?: $target;
        $rootReal = realpath($projectRoot) ?: $projectRoot;
        if (str_contains($target, '..') || ($real !== false && ! str_starts_with($real, $rootReal))) {
            throw new \InvalidArgumentException("Refusing to write outside project root: {$target}");
        }

        return $target;
    }
}
