<?php

declare(strict_types=1);

use App\Domains\IncidentCategories\Models\IncidentCategory;
use App\Domains\Incidents\Models\Incident;
use App\Domains\Locations\Models\Location;
use App\Domains\Organizations\Models\Organization;
use App\Domains\Roles\Models\Role;
use App\Domains\Sessions\Http\Middleware\JwtAuthenticate;
use App\Domains\Users\Models\User;
use Illuminate\Auth\Middleware\Authorize;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\DB;
use MatanYadaev\EloquentSpatial\Objects\Point;

/**
 * Tests for the `bbox` query parameter on `GET /api/incidents`.
 *
 * Scenarios that exercise the PostGIS `ST_Within(...)` predicate
 * (SCEN-1.2 / 1.3 / 1.5) require PostgreSQL+PostGIS — `composer test`
 * runs exclusively against Postgres (backend-tests-postgres-migration,
 * issue #197; see `backend/phpunit.xml` and
 * `.github/workflows/ci.yml`), so these always execute for real, no
 * driver check needed. Validation-only scenarios (SCEN-1.1 / 1.4 / 1.6)
 * run identically on any driver because they short-circuit before the
 * spatial SQL ever executes.
 */
uses(RefreshDatabase::class);

beforeEach(function (): void {
    // The route is protected by `jwt` middleware and the controller binds
    // `authorizeResource(Incident::class, 'incident)` which checks the
    // `incidents.view` permission via the Gate. In unit tests we don't run
    // the full RBAC seeder, so we disable both middlewares.
    $this->withoutMiddleware([
        JwtAuthenticate::class,
        Authorize::class,
    ]);

    // ── Roles ───────────────────────────────────────────────
    DB::table('roles')->insertOrIgnore([
        ['id' => 1, 'name' => 'admin_sistema'],
        ['id' => 2, 'name' => 'admin_organizacion'],
        ['id' => 3, 'name' => 'operador_organizacion'],
        ['id' => 4, 'name' => 'publicador'],
        ['id' => 5, 'name' => 'usuario'],
    ]);

    $this->location = Location::create(['name' => 'Machala', 'level' => 'city']);

    $this->orgA = Organization::create([
        'name' => 'Org A',
        'location_id' => $this->location->id,
    ]);
    $this->orgB = Organization::create([
        'name' => 'Org B',
        'location_id' => $this->location->id,
    ]);

    $this->category = IncidentCategory::create([
        'name' => 'General',
        'organization_id' => $this->orgA->id,
    ]);

    $this->systemAdmin = User::factory()->create([
        'role_id' => Role::where('name', 'admin_sistema')->first()->id,
        'organization_id' => null,
    ]);

    // Three seed incidents (no geom) — used by SCEN-1.1.
    foreach (range(1, 3) as $i) {
        Incident::create([
            'title' => "Seed incident #{$i}",
            'incident_category_id' => $this->category->id,
            'user_id' => $this->systemAdmin->id,
            'location_id' => $this->location->id,
            'organization_id' => $this->orgA->id,
            'status' => 'pending',
            'priority' => 'medium',
        ]);
    }
});

// ──────────────────────────────────────────────────────────────
// SCEN-1.1: sin bbox el endpoint se comporta idéntico al index previo
// ──────────────────────────────────────────────────────────────

it('SCEN-1.1: without bbox the index endpoint returns all incidents as before', function (): void {
    $this->actingAs($this->systemAdmin);

    $response = $this->getJson('/api/incidents');

    $response->assertOk();
    $response->assertJsonPath('meta.total', 3);

    $ids = collect($response->json('data'))->pluck('id')->all();
    expect($ids)->toHaveCount(3);
});

// ──────────────────────────────────────────────────────────────
// SCEN-1.2: bbox que cubre Machala sólo devuelve incidencias dentro del rectángulo
// ──────────────────────────────────────────────────────────────

it('SCEN-1.2: bbox filter returns only incidents whose geom lies inside the envelope', function (): void {
    $this->actingAs($this->systemAdmin);

    // Machala-ish box: lng ∈ [-80.8, -80.6], lat ∈ [-1.0, -0.8]
    //
    // NOTE on edges: ST_Within between a Point and an envelope generated by
    // ST_MakeEnvelope treats boundary inclusion differently across PostGIS
    // versions and depending on which edge the point lands on (PostGIS 3.5
    // does NOT guarantee inclusion of points exactly on the envelope's
    // minimum boundary — verified empirically). The frontend over-fetches
    // by a small margin anyway, so we don't depend on edge inclusion here.
    //
    // - inside the box       → -80.7, -0.9  (well inside)
    // - inside, near edge    → -80.65, -0.85 (close to maxLng/maxLat — still inside)
    // - outside south        → -80.7, -1.1  (below minLat)
    // - outside east         → -78.5, -0.9  (Quito — beyond maxLng)
    Incident::create([
        'title' => 'Inside Machala box (center)',
        'incident_category_id' => $this->category->id,
        'user_id' => $this->systemAdmin->id,
        'location_id' => $this->location->id,
        'organization_id' => $this->orgA->id,
        'status' => 'pending',
        'priority' => 'medium',
        'geom' => new Point(-0.9, -80.7, 4326),
    ]);
    Incident::create([
        'title' => 'Inside Machala box (near NE corner)',
        'incident_category_id' => $this->category->id,
        'user_id' => $this->systemAdmin->id,
        'location_id' => $this->location->id,
        'organization_id' => $this->orgA->id,
        'status' => 'pending',
        'priority' => 'medium',
        'geom' => new Point(-0.85, -80.65, 4326),
    ]);
    Incident::create([
        'title' => 'Outside south of box',
        'incident_category_id' => $this->category->id,
        'user_id' => $this->systemAdmin->id,
        'location_id' => $this->location->id,
        'organization_id' => $this->orgA->id,
        'status' => 'pending',
        'priority' => 'medium',
        'geom' => new Point(-1.1, -80.7, 4326),
    ]);
    Incident::create([
        'title' => 'Outside east of box (Quito)',
        'incident_category_id' => $this->category->id,
        'user_id' => $this->systemAdmin->id,
        'location_id' => $this->location->id,
        'organization_id' => $this->orgA->id,
        'status' => 'pending',
        'priority' => 'medium',
        'geom' => new Point(-0.9, -78.5, 4326),
    ]);

    $response = $this->getJson('/api/incidents?bbox=-80.8,-1.0,-80.6,-0.8');

    $response->assertOk();
    $titles = collect($response->json('data'))->pluck('title')->all();

    expect($titles)->toContain('Inside Machala box (center)');
    expect($titles)->toContain('Inside Machala box (near NE corner)');
    expect($titles)->not->toContain('Outside south of box');
    expect($titles)->not->toContain('Outside east of box (Quito)');
    expect($titles)->not->toContain('Seed incident #1');
    expect($titles)->not->toContain('Seed incident #2');
    expect($titles)->not->toContain('Seed incident #3');
});

// ──────────────────────────────────────────────────────────────
// SCEN-1.3: bbox compone con multitenant (SystemAdmin ve todo, OrgAdmin sólo lo suyo)
// ──────────────────────────────────────────────────────────────

it('SCEN-1.3: bbox composes with multitenant scoping', function (): void {
    // Org A inside the box
    $orgAIncident = Incident::create([
        'title' => 'Org A inside box',
        'incident_category_id' => $this->category->id,
        'user_id' => $this->systemAdmin->id,
        'location_id' => $this->location->id,
        'organization_id' => $this->orgA->id,
        'status' => 'pending',
        'priority' => 'medium',
        'geom' => new Point(-0.9, -80.7, 4326),
    ]);

    // Org B inside the box (different tenant, same coords)
    $categoryB = IncidentCategory::create([
        'name' => 'General B',
        'organization_id' => $this->orgB->id,
    ]);
    Incident::create([
        'title' => 'Org B inside box',
        'incident_category_id' => $categoryB->id,
        'user_id' => $this->systemAdmin->id,
        'location_id' => $this->location->id,
        'organization_id' => $this->orgB->id,
        'status' => 'pending',
        'priority' => 'medium',
        'geom' => new Point(-0.9, -80.7, 4326),
    ]);

    $url = '/api/incidents?bbox=-80.8,-1.0,-80.6,-0.8';

    // SystemAdmin sees both (Org A + Org B) inside the box
    $this->actingAs($this->systemAdmin);
    $adminResponse = $this->getJson($url);
    $adminResponse->assertOk();
    $adminTitles = collect($adminResponse->json('data'))->pluck('title')->all();
    expect($adminTitles)->toContain('Org A inside box');
    expect($adminTitles)->toContain('Org B inside box');

    // Operator from Org A only sees Org A's incidents in the box.
    // EloquentIncidentRepository::applyFilters() scopes `operador_organizacion`
    // to incidents they are explicitly assigned to (REQ-RBAC-03) — an
    // org match alone is not enough, so the operator must be assigned
    // here for the "sees it" half of this assertion to be meaningful.
    $operatorA = User::factory()->create([
        'role_id' => 3, // operador_organizacion
        'organization_id' => $this->orgA->id,
    ]);
    DB::table('assignments')->insert([
        'incident_id' => $orgAIncident->id,
        'user_id' => $operatorA->id,
        'assignment_role' => 'responsable',
        'created_at' => now(),
        'updated_at' => now(),
    ]);
    $this->actingAs($operatorA);
    $opResponse = $this->getJson($url);
    $opResponse->assertOk();
    $opTitles = collect($opResponse->json('data'))->pluck('title')->all();
    expect($opTitles)->toContain('Org A inside box');
    expect($opTitles)->not->toContain('Org B inside box');
});

// ──────────────────────────────────────────────────────────────
// SCEN-1.4: bbox con formato inválido → 422
// ──────────────────────────────────────────────────────────────

it('SCEN-1.4: malformed bbox string returns 422 validation error', function (): void {
    $this->actingAs($this->systemAdmin);

    $response = $this->getJson('/api/incidents?bbox=abc');

    $response->assertStatus(422);
    $response->assertJsonValidationErrors(['bbox']);
});

// ──────────────────────────────────────────────────────────────
// SCEN-1.5: bbox válido sin coincidencias → 200 con data vacía
// ──────────────────────────────────────────────────────────────

it('SCEN-1.5: valid bbox that contains no incidents returns 200 with empty data', function (): void {
    $this->actingAs($this->systemAdmin);

    // Box over the Pacific Ocean — well away from any seed incident.
    $response = $this->getJson('/api/incidents?bbox=-150.0,-10.0,-140.0,0.0');

    $response->assertOk();
    $response->assertJsonPath('meta.total', 0);
    $response->assertJsonPath('data', []);
});

// ──────────────────────────────────────────────────────────────
// SCEN-1.6: zoom fuera de [1,22] → 422
// ──────────────────────────────────────────────────────────────

it('SCEN-1.6: zoom outside 1..22 returns 422 validation error', function (): void {
    $this->actingAs($this->systemAdmin);

    foreach ([0, 23, 99, -5] as $bad) {
        $response = $this->getJson('/api/incidents?zoom='.$bad);
        $response->assertStatus(422);
        $response->assertJsonValidationErrors(['zoom']);
    }

    // Boundary values are accepted.
    foreach ([1, 22] as $good) {
        $response = $this->getJson('/api/incidents?zoom='.$good);
        $response->assertOk();
    }
});
