global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'backend'
    dns_sd_configs:
      - names: ['tasks.backend']
        type: A
        port: 8000
    metrics_path: '/metrics'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance

  - job_name: 'nginx'
    dns_sd_configs:
      - names: ['tasks.frontend']
        type: A
        port: 80
    metrics_path: '/nginx_status'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres_exporter:9187']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis_exporter:9121']
